### ISSUE TITLE
اوقات الصلاة غير دقيقة (متقدمة) بفرق ساعات

### ISSUE THREAD

**Issue by fahad9022** [alhazmy13/PrayerTimes#1]

**Comment by alhazmy13** [comment]
تاكد من ضبط الاعدادات بشكل صحيح لتناسب المذهب المتبع في منطقتك

**Comment by fahad9022** [comment]
هل عندك طريقة لمعرفة 
خطوط الطول والعرض للمدينة بشكل عام
لان المشكلة دايما انها بتكون 0

**Comment by alhazmy13** [comment]
استخدم خرائط قوقل لجلب الاحداثيات بشكل يدوي او استخدم 
Google play service من خلال الاندرويد
